"""
txcore.catalog.seeder
~~~~~~~~~~~~~~~~~~~~~
Idempotent startup database seeder for AuraTrade Module 2: Market Catalog.
Pre-seeds benchmark market groups and standard symbols across 5 asset classes:
- Indian Equities & Indices (NSE / BSE)
- US Equities & Indices (NASDAQ / NYSE)
- Crypto Pairs (Binance)
- Forex Pairs (FX_IDC)
- MCX Commodities (MCX)

Enforces strict decimal precision:
- 4 decimal places (0.0001) for stocks & indices
- 6 decimal places (0.000001) for crypto, forex, and commodities
All records include standardized institutional audit metadata (createdBy = "SYSTEM_SEEDER").
"""

import logging
from typing import List, Dict, Any
from txcore.database import db

logger = logging.getLogger("auratrade.catalog.seeder")

# =========================================================================
# 1. Market Groups Definitions
# =========================================================================
BENCHMARK_GROUPS: List[Dict[str, Any]] = [
    {
        "groupId": "NSE",
        "name": "National Stock Exchange (India)",
        "market": "INDIAN_EQUITY",
        "description": "NSE Top Liquid Equities & Sectoral Benchmark Indices",
    },
    {
        "groupId": "US_EQUITY",
        "name": "US Equities & Major ETFs",
        "market": "US_EQUITY",
        "description": "Mega-Cap US Equities, S&P 500 and Nasdaq 100 Benchmarks",
    },
    {
        "groupId": "CRYPTO",
        "name": "Cryptocurrency Markets",
        "market": "CRYPTO",
        "description": "High-Volume Liquid Crypto Pairs on Binance Spot",
    },
    {
        "groupId": "FOREX",
        "name": "Foreign Exchange Markets",
        "market": "FOREX",
        "description": "Major and Liquid Cross-Currency Pairs",
    },
    {
        "groupId": "MCX",
        "name": "Multi Commodity Exchange (India)",
        "market": "MCX",
        "description": "Precious Metals, Energy, and Industrial Commodities",
    },
]

# =========================================================================
# 2. Benchmark Symbols Definitions
# =========================================================================
BENCHMARK_SYMBOLS: List[Dict[str, Any]] = [
    # --- Indian Benchmark Indices (4 Decimals) ---
    {
        "symbol": "NIFTY",
        "shortName": "NIFTY 50",
        "fullName": "NIFTY 50 Benchmark Index",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "INDEX",
        "indexGroup": "BENCHMARK",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:NIFTY",
    },
    {
        "symbol": "BANKNIFTY",
        "shortName": "NIFTY Bank",
        "fullName": "NIFTY Bank Index",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "INDEX",
        "indexGroup": "SECTORAL",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:BANKNIFTY",
    },
    {
        "symbol": "FINNIFTY",
        "shortName": "NIFTY Financial",
        "fullName": "NIFTY Financial Services Index",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "INDEX",
        "indexGroup": "SECTORAL",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:FINNIFTY",
    },
    {
        "symbol": "MIDCPNIFTY",
        "shortName": "NIFTY Midcap",
        "fullName": "NIFTY Midcap Select Index",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "INDEX",
        "indexGroup": "BENCHMARK",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:MIDCPNIFTY",
    },
    {
        "symbol": "SENSEX",
        "shortName": "BSE SENSEX",
        "fullName": "S&P BSE SENSEX Index",
        "market": "INDIAN_EQUITY",
        "exchange": "BSE",
        "assetType": "INDEX",
        "indexGroup": "BENCHMARK",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "BSE:SENSEX",
    },
    {
        "symbol": "INDIAVIX",
        "shortName": "India VIX",
        "fullName": "India Volatility Index",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "INDEX",
        "indexGroup": "VOLATILITY",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:INDIAVIX",
    },
    # --- Indian Equities (4 Decimals) ---
    {
        "symbol": "RELIANCE",
        "shortName": "Reliance",
        "fullName": "Reliance Industries Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Energy",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:RELIANCE",
    },
    {
        "symbol": "TCS",
        "shortName": "TCS",
        "fullName": "Tata Consultancy Services Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Information Technology",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:TCS",
    },
    {
        "symbol": "HDFCBANK",
        "shortName": "HDFC Bank",
        "fullName": "HDFC Bank Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Banking",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:HDFCBANK",
    },
    {
        "symbol": "INFY",
        "shortName": "Infosys",
        "fullName": "Infosys Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Information Technology",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:INFY",
    },
    {
        "symbol": "ICICIBANK",
        "shortName": "ICICI Bank",
        "fullName": "ICICI Bank Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Banking",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:ICICIBANK",
    },
    {
        "symbol": "SBIN",
        "shortName": "SBI",
        "fullName": "State Bank of India",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "PSU Banking",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:SBIN",
    },
    {
        "symbol": "BHARTIARTL",
        "shortName": "Airtel",
        "fullName": "Bharti Airtel Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Telecom",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:BHARTIARTL",
    },
    {
        "symbol": "ITC",
        "shortName": "ITC",
        "fullName": "ITC Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "FMCG",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:ITC",
    },
    {
        "symbol": "LT",
        "shortName": "L&T",
        "fullName": "Larsen & Toubro Ltd",
        "market": "INDIAN_EQUITY",
        "exchange": "NSE",
        "assetType": "STOCK",
        "sector": "Infrastructure",
        "indexGroup": "NIFTY50",
        "decimalPlaces": 4,
        "groupId": "NSE",
        "lotSize": 1,
        "tickSize": 0.05,
        "tvSymbol": "NSE:LT",
    },
    # --- US Indices & Mega-Cap Equities (4 Decimals) ---
    {
        "symbol": "SPY",
        "shortName": "SPY",
        "fullName": "SPDR S&P 500 ETF Trust",
        "market": "US_EQUITY",
        "exchange": "NYSE",
        "assetType": "INDEX",
        "indexGroup": "BENCHMARK",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "AMEX:SPY",
    },
    {
        "symbol": "QQQ",
        "shortName": "QQQ",
        "fullName": "Invesco QQQ Trust Series 1",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "INDEX",
        "indexGroup": "BENCHMARK",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:QQQ",
    },
    {
        "symbol": "AAPL",
        "shortName": "Apple",
        "fullName": "Apple Inc",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Technology",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:AAPL",
    },
    {
        "symbol": "MSFT",
        "shortName": "Microsoft",
        "fullName": "Microsoft Corp",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Technology",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:MSFT",
    },
    {
        "symbol": "NVDA",
        "shortName": "NVIDIA",
        "fullName": "NVIDIA Corp",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Semiconductors",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:NVDA",
    },
    {
        "symbol": "TSLA",
        "shortName": "Tesla",
        "fullName": "Tesla Inc",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Consumer Cyclical",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:TSLA",
    },
    {
        "symbol": "AMZN",
        "shortName": "Amazon",
        "fullName": "Amazon.com Inc",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Consumer Cyclical",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:AMZN",
    },
    {
        "symbol": "GOOGL",
        "shortName": "Alphabet",
        "fullName": "Alphabet Inc Class A",
        "market": "US_EQUITY",
        "exchange": "NASDAQ",
        "assetType": "STOCK",
        "sector": "Communication",
        "indexGroup": "MAG7",
        "decimalPlaces": 4,
        "groupId": "US_EQUITY",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "NASDAQ:GOOGL",
    },
    # --- Crypto Pairs (6 Decimals) ---
    {
        "symbol": "BTCUSDT",
        "shortName": "Bitcoin",
        "fullName": "Bitcoin / Tether USD",
        "market": "CRYPTO",
        "exchange": "BINANCE",
        "assetType": "CRYPTO",
        "decimalPlaces": 6,
        "groupId": "CRYPTO",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "BINANCE:BTCUSDT",
    },
    {
        "symbol": "ETHUSDT",
        "shortName": "Ethereum",
        "fullName": "Ethereum / Tether USD",
        "market": "CRYPTO",
        "exchange": "BINANCE",
        "assetType": "CRYPTO",
        "decimalPlaces": 6,
        "groupId": "CRYPTO",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "BINANCE:ETHUSDT",
    },
    {
        "symbol": "SOLUSDT",
        "shortName": "Solana",
        "fullName": "Solana / Tether USD",
        "market": "CRYPTO",
        "exchange": "BINANCE",
        "assetType": "CRYPTO",
        "decimalPlaces": 6,
        "groupId": "CRYPTO",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "BINANCE:SOLUSDT",
    },
    {
        "symbol": "BNBUSDT",
        "shortName": "BNB",
        "fullName": "BNB / Tether USD",
        "market": "CRYPTO",
        "exchange": "BINANCE",
        "assetType": "CRYPTO",
        "decimalPlaces": 6,
        "groupId": "CRYPTO",
        "lotSize": 1,
        "tickSize": 0.01,
        "tvSymbol": "BINANCE:BNBUSDT",
    },
    {
        "symbol": "XRPUSDT",
        "shortName": "XRP",
        "fullName": "Ripple XRP / Tether USD",
        "market": "CRYPTO",
        "exchange": "BINANCE",
        "assetType": "CRYPTO",
        "decimalPlaces": 6,
        "groupId": "CRYPTO",
        "lotSize": 1,
        "tickSize": 0.0001,
        "tvSymbol": "BINANCE:XRPUSDT",
    },
    # --- Forex Pairs (6 Decimals) ---
    {
        "symbol": "EURUSD",
        "shortName": "EUR/USD",
        "fullName": "Euro / US Dollar",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.0001,
        "tvSymbol": "FX_IDC:EURUSD",
    },
    {
        "symbol": "GBPUSD",
        "shortName": "GBP/USD",
        "fullName": "British Pound / US Dollar",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.0001,
        "tvSymbol": "FX_IDC:GBPUSD",
    },
    {
        "symbol": "USDJPY",
        "shortName": "USD/JPY",
        "fullName": "US Dollar / Japanese Yen",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.001,
        "tvSymbol": "FX_IDC:USDJPY",
    },
    {
        "symbol": "USDINR",
        "shortName": "USD/INR",
        "fullName": "US Dollar / Indian Rupee",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.0025,
        "tvSymbol": "FX_IDC:USDINR",
    },
    {
        "symbol": "USDCHF",
        "shortName": "USD/CHF",
        "fullName": "US Dollar / Swiss Franc",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.0001,
        "tvSymbol": "FX_IDC:USDCHF",
    },
    {
        "symbol": "AUDUSD",
        "shortName": "AUD/USD",
        "fullName": "Australian Dollar / US Dollar",
        "market": "FOREX",
        "exchange": "FX_IDC",
        "assetType": "FOREX",
        "decimalPlaces": 6,
        "groupId": "FOREX",
        "lotSize": 1000,
        "tickSize": 0.0001,
        "tvSymbol": "FX_IDC:AUDUSD",
    },
    # --- MCX Commodities (6 Decimals) ---
    {
        "symbol": "GOLD",
        "shortName": "Gold",
        "fullName": "MCX Gold Commodity",
        "market": "MCX",
        "exchange": "MCX",
        "assetType": "COMMODITY",
        "decimalPlaces": 6,
        "groupId": "MCX",
        "lotSize": 1,
        "tickSize": 1.0,
        "tvSymbol": "MCX:GOLD1!",
    },
    {
        "symbol": "SILVER",
        "shortName": "Silver",
        "fullName": "MCX Silver Commodity",
        "market": "MCX",
        "exchange": "MCX",
        "assetType": "COMMODITY",
        "decimalPlaces": 6,
        "groupId": "MCX",
        "lotSize": 1,
        "tickSize": 1.0,
        "tvSymbol": "MCX:SILVER1!",
    },
    {
        "symbol": "CRUDEOIL",
        "shortName": "Crude Oil",
        "fullName": "MCX Crude Oil Commodity",
        "market": "MCX",
        "exchange": "MCX",
        "assetType": "COMMODITY",
        "decimalPlaces": 6,
        "groupId": "MCX",
        "lotSize": 1,
        "tickSize": 1.0,
        "tvSymbol": "MCX:CRUDEOIL1!",
    },
    {
        "symbol": "NATURALGAS",
        "shortName": "Natural Gas",
        "fullName": "MCX Natural Gas Commodity",
        "market": "MCX",
        "exchange": "MCX",
        "assetType": "COMMODITY",
        "decimalPlaces": 6,
        "groupId": "MCX",
        "lotSize": 1,
        "tickSize": 0.1,
        "tvSymbol": "MCX:NATURALGAS1!",
    },
]


async def seed_benchmarks() -> Dict[str, int]:
    """
    Idempotent seeder:
    1. Upserts default MarketGroups.
    2. Upserts benchmark MarketSymbols with strict precision and audit columns.
    Returns:
        Dict with count of groups and symbols processed.
    """
    logger.info("Initiating AuraTrade benchmark catalog seeding...")

    # 1. Seed Groups
    groups_seeded = 0
    for g in BENCHMARK_GROUPS:
        existing = await db.marketgroup.find_unique(where={"groupId": g["groupId"]})
        if not existing:
            await db.marketgroup.create(
                data={
                    "groupId": g["groupId"],
                    "name": g["name"],
                    "market": g["market"],
                    "description": g["description"],
                    "createdBy": "SYSTEM_SEEDER",
                    "updatedBy": "SYSTEM_SEEDER",
                }
            )
            groups_seeded += 1
            logger.info(f"Seeded market group: {g['groupId']}")
        else:
            # Update fields if needed
            await db.marketgroup.update(
                where={"groupId": g["groupId"]},
                data={
                    "name": g["name"],
                    "market": g["market"],
                    "description": g["description"],
                    "updatedBy": "SYSTEM_SEEDER",
                },
            )

    # 2. Seed Symbols
    symbols_seeded = 0
    for s in BENCHMARK_SYMBOLS:
        existing_symbol = await db.marketsymbol.find_unique(where={"symbol": s["symbol"]})
        if not existing_symbol:
            await db.marketsymbol.create(
                data={
                    "symbol": s["symbol"],
                    "shortName": s["shortName"],
                    "fullName": s["fullName"],
                    "market": s["market"],
                    "exchange": s["exchange"],
                    "assetType": s["assetType"],
                    "sector": s.get("sector"),
                    "indexGroup": s.get("indexGroup"),
                    "decimalPlaces": s["decimalPlaces"],
                    "groupId": s["groupId"],
                    "lotSize": s.get("lotSize", 1),
                    "tickSize": s.get("tickSize", 0.05),
                    "tvSymbol": s.get("tvSymbol"),
                    "isPreseeded": True,
                    "isActive": True,
                    "createdBy": "SYSTEM_SEEDER",
                    "updatedBy": "SYSTEM_SEEDER",
                }
            )
            symbols_seeded += 1
        else:
            # Update metadata while preserving user toggles (isActive)
            await db.marketsymbol.update(
                where={"symbol": s["symbol"]},
                data={
                    "shortName": s["shortName"],
                    "fullName": s["fullName"],
                    "market": s["market"],
                    "exchange": s["exchange"],
                    "assetType": s["assetType"],
                    "sector": s.get("sector"),
                    "indexGroup": s.get("indexGroup"),
                    "decimalPlaces": s["decimalPlaces"],
                    "groupId": s["groupId"],
                    "lotSize": s.get("lotSize", 1),
                    "tickSize": s.get("tickSize", 0.05),
                    "tvSymbol": s.get("tvSymbol"),
                    "isPreseeded": True,
                    "updatedBy": "SYSTEM_SEEDER",
                },
            )

    total_groups = await db.marketgroup.count()
    total_symbols = await db.marketsymbol.count()
    logger.info(
        f"Seeding completed. Total Groups: {total_groups} (+{groups_seeded}), "
        f"Total Symbols: {total_symbols} (+{symbols_seeded})"
    )

    return {
        "groups_seeded": groups_seeded,
        "symbols_seeded": symbols_seeded,
        "total_groups": total_groups,
        "total_symbols": total_symbols,
    }
